export const baseUrl = 'http://localhost:8000'
export const loginUrl = baseUrl + '/auth/login'
export const refreshUrl = baseUrl + '/auth/refresh'
export const signupUrl = baseUrl + '/auth/signup'
export const logoutUrl = baseUrl + '/auth/logout'

export const userIdentityUrl = baseUrl + '/user/user-identity'
export const userUrl = baseUrl + '/user/user-info/'
export const usersUrl = baseUrl + '/user/all'
export const unfollowedUsersUrl = baseUrl + '/user/unfollowed'
export const userUpdateBioUrl = baseUrl + '/user/update-bio'
export const toggleFollowUrl = baseUrl + '/user/toggle-follow'

export const csrfTokenUrl = baseUrl + '/get-csrf-token'

export const tweetsUrl = baseUrl + '/tweet/all'
export const followingTweetsUrl = baseUrl + '/tweet/following'
export const repliesUrl = baseUrl + '/tweet/replies/'
export const tweetsByAuthorUrl = baseUrl + '/tweet/get-by-author/'
export const tweetUrl = baseUrl + '/tweet/get/'
export const parentTweetUrl = baseUrl + '/tweet/get-parent-tweet/'
export const authorUrl = baseUrl + '/tweet/get-author/'
export const newTweetUrl = baseUrl + '/tweet/create'
export const toggleLikeTweetUrl = baseUrl + '/tweet/toggle-like'
export const toggleRetweetUrl = baseUrl + '/tweet/toggle-retweet'