"""empty message

Revision ID: 09d634f609a6
Revises: 6139f1c74820
Create Date: 2024-02-11 14:55:49.608078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d634f609a6'
down_revision = '6139f1c74820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_retweet_of', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.drop_column('is_retweet_of')

    # ### end Alembic commands ###
