"""empty message

Revision ID: 0d5a4c5cea88
Revises: 899a8067a1de
Create Date: 2023-12-27 11:55:07.601356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d5a4c5cea88'
down_revision = '899a8067a1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('joined_date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('joined_date')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
