"""empty message

Revision ID: 6139f1c74820
Revises: af495b4ac3b8
Create Date: 2024-02-01 15:43:12.220358

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6139f1c74820'
down_revision = 'af495b4ac3b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.alter_column('photos',
               existing_type=postgresql.ARRAY(postgresql.BYTEA()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=False)
        batch_op.alter_column('video',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('cover',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('cover',
               existing_type=sa.String(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
        batch_op.alter_column('avatar',
               existing_type=sa.String(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)

    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.alter_column('video',
               existing_type=sa.String(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
        batch_op.alter_column('photos',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(postgresql.BYTEA()),
               existing_nullable=False)

    # ### end Alembic commands ###
