"""empty message

Revision ID: 899a8067a1de
Revises: 9f28f7ef9bc6
Create Date: 2023-12-27 09:27:47.030298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899a8067a1de'
down_revision = '9f28f7ef9bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('cover', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('cover')
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
