"""empty message

Revision ID: 9f28f7ef9bc6
Revises: 
Create Date: 2023-12-27 09:18:41.973830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f28f7ef9bc6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('cover', sa.LargeBinary(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('cover')
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
